[package]
name = "constmuck"
version = "0.0.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2021"
license = "Zlib"
description = "WORK IN PROGRESS: const-equivalents of bytemuck functions, and more"
documentation = "https://docs.rs/constmuck/"
readme="./README.md"
keywords = ["no-std", "transmute", "casting", "const-fn"]
categories = ["no-std"]
repository = "https://github.com/rodrimati1992/constmuck/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "README.md",
    "LICENSE-ZLIB.md", 
]

[dependencies.bytemuck]
version = "1.7.2"
features = ["min_const_generics"]